(function(){
'use strict';
const $=s=>document.querySelector(s),enc=new TextEncoder();
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function b64ToBytes(s){const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
function unb64url(s){let x=s.replace(/-/g,'+').replace(/_/g,'/');while(x.length%4)x+='=';return b64ToBytes(x)}
function bytesToB64url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fmtDateTime(iso){try{return new Intl.DateTimeFormat('es-MX',{day:'2-digit',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso))}catch{return iso}}
async function sha256Bytes(data){return new Uint8Array(await crypto.subtle.digest('SHA-256',data instanceof Uint8Array?data:enc.encode(data)))}
async function keyFingerprint(publicJwk){const d=await sha256Bytes(`${publicJwk.x}.${publicJwk.y}`);return Array.from(d.slice(0,8)).map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase().match(/.{1,4}/g).join('-')}
function supabaseConfigured(){const c=window.RX_SUPABASE_CONFIG||{};return /^https:\/\/.+\.supabase\.co$/i.test(String(c.url||''))&&String(c.publishableKey||'').length>20&&!String(c.publishableKey).includes('PASTE_')}
async function decodeToken(raw){if(raw.startsWith('z.')){const bytes=unb64url(raw.slice(2));if(!('DecompressionStream' in window))throw new Error('Este navegador no puede descomprimir el paquete de verificación. Usa Safari, Chrome o Brave actualizado.');const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(new TextDecoder().decode(new Uint8Array(await new Response(stream).arrayBuffer())))}if(raw.startsWith('j.'))return JSON.parse(new TextDecoder().decode(unb64url(raw.slice(2))));return JSON.parse(new TextDecoder().decode(unb64url(raw)))}
function expandPacket(packet){if(packet?.v===3){const d=packet.d||[],p=packet.p||[],e=packet.e||[];const canonical={v:1,id:packet.i,issuedAt:packet.t,doctor:{name:d[0]||'',role:d[1]||'',license:d[2]||'',university:d[3]||'',address:d[4]||'',phone:d[5]||'',email:d[6]||''},patient:{id:p[0]||'',name:p[1]||'',dob:p[2]||'',age:p[3]??null,sex:p[4]||'',allergies:p[5]||'',weight:p[6]||''},medications:(packet.m||[]).map(x=>({name:x[0]||'',brand:x[1]||'',strength:x[2]||'',dose:x[3]||'',route:x[4]||'',frequency:x[5]||'',duration:x[6]||'',instructions:x[7]||''})),general:packet.g||'',signatureImageSha256:packet.h||'',design:{theme:e[0]||'',primary:e[1]||'',secondary:e[2]||''}};const publicJwk={kty:'EC',crv:'P-256',x:packet.k?.[0]||'',y:packet.k?.[1]||'',ext:true};return {canonical,signature:packet.s||'',publicJwk,algorithm:'ECDSA-P256-SHA256'}}if(packet?.canonical&&packet?.seal)return {canonical:packet.canonical,signature:packet.seal.signature,publicJwk:packet.seal.publicJwk,algorithm:packet.seal.algorithm||'ECDSA-P256-SHA256',claimedHash:packet.seal.hash,claimedFingerprint:packet.seal.keyFingerprint};throw new Error('El enlace no contiene un paquete de verificación válido.')}
async function verifyPacket(packet){const x=expandPacket(packet),canonicalJson=JSON.stringify(x.canonical),calcHash=bytesToB64url(await sha256Bytes(canonicalJson));if(x.claimedHash&&x.claimedHash!==calcHash)return {...x,ok:false,hashOk:false,signatureOk:false,calcHash,fingerprint:await keyFingerprint(x.publicJwk),registryMatch:null,cloud:false};const pub=await crypto.subtle.importKey('jwk',x.publicJwk,{name:'ECDSA',namedCurve:'P-256'},false,['verify']);const signatureOk=await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},pub,unb64url(x.signature),enc.encode(canonicalJson));const fingerprint=await keyFingerprint(x.publicJwk);return {...x,ok:signatureOk,hashOk:true,signatureOk,calcHash,fingerprint,registryMatch:null,cloud:false,status:'issued'}}
async function verifyCloudToken(token){if(!supabaseConfigured())throw new Error('El verificador de nube todavía no está configurado en esta instalación.');const c=window.RX_SUPABASE_CONFIG;let r;try{r=await fetch(String(c.url).replace(/\/$/,'')+'/rest/v1/rpc/verify_prescription',{method:'POST',headers:{'apikey':c.publishableKey,'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({p_token:token})})}catch{throw new Error('No se pudo conectar con el servidor de verificación. Intenta nuevamente cuando haya conexión.')}const text=await r.text();let data=null;if(text){try{data=JSON.parse(text)}catch{data=text}}if(!r.ok)throw new Error(data?.message||data?.error||`Error de verificación HTTP ${r.status}`);if(!data||data.found!==true)throw new Error('No existe una receta con este token o todavía no ha sido sincronizada.');const canonicalJson=data.canonical_text,canonical=JSON.parse(canonicalJson),seal=data.seal||{},calcHash=bytesToB64url(await sha256Bytes(canonicalJson));const hashOk=calcHash===seal.hash;let signatureOk=false,fingerprint='—',registryMatch=false;if(seal.publicJwk){fingerprint=await keyFingerprint(seal.publicJwk);registryMatch=fingerprint===data.registered_key_fingerprint&&seal.keyFingerprint===data.registered_key_fingerprint&&seal.publicJwk.x===data.registered_public_jwk?.x&&seal.publicJwk.y===data.registered_public_jwk?.y;if(hashOk){const pub=await crypto.subtle.importKey('jwk',seal.publicJwk,{name:'ECDSA',namedCurve:'P-256'},false,['verify']);signatureOk=await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},pub,unb64url(seal.signature),enc.encode(canonicalJson))}}return {canonical,algorithm:seal.algorithm||'ECDSA-P256-SHA256',calcHash,fingerprint,hashOk,signatureOk,registryMatch,ok:hashOk&&signatureOk&&registryMatch&&data.physician_key_active!==false,status:data.status||'issued',voidedAt:data.voided_at||null,voidReason:data.void_reason||'',cloud:true}}
function showStatus(kind,title,detail){const box=$('#statusBox');box.className='status '+kind;box.textContent=title;$('#statusDetail').textContent=detail}
function showCards(){['#summaryCard','#rxCard','#techCard'].forEach(id=>$(id).style.display='block')}
function medHtml(m,i){return `<div class="med"><strong>${i+1}. ${esc(m.name)}${m.brand?' ('+esc(m.brand)+')':''} · ${esc(m.strength)}</strong><div>${esc(m.dose)} · Vía ${esc(m.route)} · ${esc(m.frequency)} · ${esc(m.duration)}</div>${m.instructions?`<div class="muted" style="margin-top:4px">${esc(m.instructions)}</div>`:''}</div>`}
function renderResult(result){const c=result.canonical;showCards();$('#vId').textContent=c.id||'—';$('#vIssuedAt').textContent=fmtDateTime(c.issuedAt||'');$('#vDoctor').textContent=c.doctor?.name||'—';$('#vLicense').textContent=c.doctor?.license||'—';$('#vPatient').textContent=c.patient?.name||'—';$('#vState').textContent=result.status==='void'?'ANULADA':(result.ok?'Vigente':'No válida');$('#vMeds').innerHTML=(c.medications||[]).map(medHtml).join('')||'<p class="muted">Sin medicamentos.</p>';$('#vGeneral').textContent=c.general||'Sin indicaciones adicionales.';$('#vAlgo').textContent=result.algorithm||'ECDSA-P256-SHA256';$('#vFp').textContent=result.fingerprint||'—';$('#vHash').textContent=result.calcHash||'—';if(result.cloud&&result.ok&&result.status==='void')showStatus('warn','✓ Receta auténtica · ANULADA',`La firma y la identidad criptográfica son válidas, pero esta receta fue anulada${result.voidedAt?' el '+fmtDateTime(result.voidedAt):''}.${result.voidReason?' Motivo: '+result.voidReason:''}`);else if(result.cloud&&result.ok)showStatus('ok','✓ RECETA AUTÉNTICA','Registro encontrado en el backend, firma válida, clave pública registrada para el médico y contenido original sin alteraciones.');else if(result.ok)showStatus('ok','✓ Receta auténtica','La firma digital coincide con el contenido exacto mostrado abajo. Esta verificación es local al QR.');else if(result.cloud&&!result.registryMatch)showStatus('bad','✕ Verificación fallida','La firma no coincide con una clave pública registrada para el médico emisor.');else showStatus('bad','✕ Verificación fallida','La firma digital o el hash no corresponden al contenido recibido.')}
async function init(){try{const raw=location.hash.slice(1);let result;if(raw.startsWith('t=')){const cloudToken=raw.slice(2);if(!cloudToken)throw new Error('Token de verificación vacío.');result=await verifyCloudToken(cloudToken)}else{if(!raw)throw new Error('Este QR no contiene datos de verificación.');result=await verifyPacket(await decodeToken(raw))}renderResult(result)}catch(err){showStatus('bad','✕ No se pudo verificar',''+err.message)}}
init();
})();
